# [line_break]
# disabled = true

# Disable the newline at the start of the prompt
add_newline = false

[aws]
symbol = "AWS "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = "Conda "

[dart]
symbol = "Dart "

[directory]
read_only = " "

[docker]
symbol = "Docker "

[elixir]
symbol = "Elixir "

[elm]
symbol = "Elm "

[git_branch]

[golang]
symbol = "Go "

[haskell]
symbol = "Haskell "

[hg_branch]

[java]
symbol = "Java "

[julia]
symbol = "Julia "

[memory_usage]
symbol = " "

[nim]
symbol = "Nim "

[nix_shell]
symbol = "Nix shell "

[nodejs]
symbol = "Node "

[package]
disabled = true

[perl]
symbol = "Perl "

[php]
symbol = "PHP "

[python]
symbol = "Python "

[ruby]
symbol = "Ruby "

[rust]
symbol = "Rust "

[swift]
symbol = "Swift "

